spring:
  application:
    name: procesa-contable-api
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: ${DB_HOST}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_ROOT_PASSWORD}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.SQLServerDialect
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  web:
    resources:
      add-mappings: false
logging:
  level:
    restClientLogger: WARN
security:
  user:
    password: ${USER_PASS}
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: ${JWT_EXPIRATION_TIME}
