name: test

on:
  pull_request:
    branches:
      - develop

jobs:
  code-coverage:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout project
        uses: actions/checkout@v4.1.1

      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with: 
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'
          
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6

      - name: Run Code Coverage
        run: mvn -f "./procesa-contable-api/pom.xml" clean test

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4.3.1
        with:
          name: code-coverage-report
          path: |
            ${{ github.workspace }}/**/build/reports/jacoco/test/html/*
            ${{ github.workspace }}/**/target/site/jacoco/*

      - name: Print GITHUB_WORKSPACE
        run: echo ${{ github.workspace }}
            
      - name: Add Code Coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/procesa-contable-api/build/reports/jacoco/test/jacocoTestReport.xml
            ${{ github.workspace }}/procesa-contable-api/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Code Coverage
          min-coverage-overall: 80
          min-coverage-changed-files: 85
          pass-emoji: ':green_circle:'
          fail-emoji: ':red_circle:'
      - name: Fail PR if overall coverage is less than 80%
        if: ${{ steps.jacoco.outputs.coverage-overall < 80 }}
        uses: actions/github-script@v7.0.1
        with: 
          script: |
            core.setFailed('Overall coverage is less than 80%!')

      - name: Fail PR if changed files coverage is less than 85%
        if: ${{ steps.jacoco.outputs.coverage-changed-files < 85 }}
        uses: actions/github-script@v7.0.1
        with:
          script: |
            core.setFailed('Changed files coverage is less than 85%!')

      - name: Print Message
        run: echo "This message will be printed during the workflow execution."
